// The ABI json generated by koinos-abi-proto-gen uses camelCase method
// fields (entryPoint, input, output, readOnly) while koilib expects
// snake_case. These helpers normalize it and build the string registered
// on-chain in the contract meta store.

import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const here = path.dirname(fileURLToPath(import.meta.url));

export function loadGeneratedAbi() {
  const abiPath = path.join(here, "../contract/abi/orderbook-abi.json");
  return JSON.parse(fs.readFileSync(abiPath, "utf8"));
}

export function toKoilibAbi(generated) {
  const methods = {};
  for (const [name, method] of Object.entries(generated.methods)) {
    const entryPoint =
      method.entry_point ??
      method.entryPoint ??
      (method["entry-point"] !== undefined
        ? parseInt(method["entry-point"], 16)
        : undefined);
    methods[name] = {
      entry_point: entryPoint,
      argument: method.argument ?? method.input,
      return: method.return ?? method.output,
      read_only: method.read_only ?? method.readOnly ?? method["read-only"],
      description: method.description,
    };
  }
  return { methods, koilib_types: generated.types };
}

export function loadOrderbookAbi() {
  return toKoilibAbi(loadGeneratedAbi());
}

/**
 * ABI string registered on-chain (contract meta store): koilib-compatible
 * methods plus both type encodings so explorers and koilib can decode
 * operations without this repository.
 */
export function buildRegisteredAbi() {
  const generated = loadGeneratedAbi();
  const koilibAbi = toKoilibAbi(generated);
  const canonicalPath = path.join(here, "../contract/abi/orderbook.abi");
  let binaryTypes;
  try {
    binaryTypes = JSON.parse(fs.readFileSync(canonicalPath, "utf8")).types;
  } catch {
    binaryTypes = undefined;
  }
  return JSON.stringify({
    methods: koilibAbi.methods,
    koilib_types: koilibAbi.koilib_types,
    ...(binaryTypes ? { types: binaryTypes } : {}),
  });
}
